# Generated by Django 5.2.13 on 2026-04-23 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_seed_subscription_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ai_model', 'AI Models'), ('design', 'Design'), ('devops', 'DevOps'), ('cloud', 'Cloud')], max_length=20)),
                ('logo_key', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('docs_url', models.CharField(blank=True, max_length=255, null=True)),
                ('config_fields', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('file_uploaded', 'File Uploaded'), ('file_deleted', 'File Deleted'), ('member_assigned', 'Member Assigned'), ('member_removed', 'Member Removed'), ('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('comment_added', 'Comment Added'), ('ai_output_generated', 'AI Output Generated'), ('status_changed', 'Status Changed'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('integration_configured', 'Integration Configured'), ('integration_toggled', 'Integration Toggled'), ('integration_removed', 'Integration Removed')], max_length=40),
        ),
        migrations.CreateModel(
            name='UserIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('is_configured', models.BooleanField(default=False)),
                ('config_data', models.JSONField(blank=True, null=True)),
                ('configured_at', models.DateTimeField(blank=True, null=True)),
                ('last_toggled_at', models.DateTimeField(blank=True, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_integrations', to='projects.integrationdefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['integration__name'],
                'unique_together': {('user', 'integration')},
            },
        ),
    ]
